Commit 1
MarinaVolk/java-filmorate pull request #3
Opened 2023-05-26 21:42 UTC by MarinaVolk

2023-05-28 10:21 UTC, TomattmanYandex requested changes
1) В проекте должна быть картинка со схемой бд, ссылка на нее должна быть в readme файле
2) Надо разобраться с хранилищами и Dao (оставить что то одно)
3) Реализации которые в памяти можно удалить
4) На любой метод в Dao должно быть 1 - 3 запроса в базу данных
если получаем список фильмов то это должен быть один запрос на получения сразу всех фильмов а не отдельный запрос под каждый фильм, дополнительные два запроса могут быть для жанров и лайков, но тоже только по одному запросу для любого количества фильмов

2023-05-28 10:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    private int id;
лучше использовать класс обертку вместо примитива

2023-05-28 10:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    private int id;
то же что и выше, класс обертка вместо примитива

2023-05-28 10:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaAndGenresController.java
> +public class MpaAndGenresController {
обычно для каждой сущности делают отдельные классы контроллеры,
следует разбить этот класс на два на MpaController и на GenreController

2023-05-28 10:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Mpa getMpaById(Integer id) {
плохой подход, в самом методе объясню почему

2023-05-28 10:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Mpa> allMpa = findAllMpa();
для того чтобы получить один обьект, мы получаем все, представь, что в базе тысячи таких обьектов, т.е. в начале мы получаем все тысячи, потом переходим по всем чтобы найти один
итого вместо сложность O(1) получаем сложность O(n+1)

2023-05-28 10:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (id > allMpa.size() || id < 1) {
Представим ситуацию, в базу добавлены 10 записей, id последней будет 10
потом первые 3 удалены
и мы ищем запись с id 10
размер списка будет 7 и все ошибка, хотя запись с таким id есть
а еще id меньше нуля - валидные id

2023-05-28 10:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        List<Integer> filmsId = jdbcTemplate.query("SELECT film_id FROM FILMS ORDER BY film_id ASC;", ((rs, rowNum) -> rs.getInt("film_id")));
вместо 1- 3 запросов будет n * 3 + 1 и даже больше
а должно быть 1-3 запроса

2023-05-28 10:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        Set<Integer> genresId = genresListDao.getGenresSetIdByFilmId(id);
1) снова момент где вместо 1 запроса  n + 1
2) жанры должны проставляться через сервис
3) при получении списка фильмов должно быть все равно 1-3 запроса для любого количества фильмов а не отдельный запрос для каждого фильма

2023-05-28 10:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    public Genre getGenreById(Integer id) {
почему методы для жанров находятся в хранилище фильмов?

2023-05-28 10:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    public Mpa getMpaById(Integer id) {
и  почему методы для mpa находятся в хранилище фильмов

2023-05-28 10:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +//@Component
1) закомментированный код не допускается
2) если оставляешь этот класс, то он должен остаться компонентом

2023-05-28 10:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +//@Component
аналогично с предыдущим

2023-05-28 10:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/dao/FilmsDao.java
> +public class FilmsDao {
По сути DAO и Storage это одно и то же, просто DAO завязано на базу данных
следовательно стоит либо удалить реализации Storage классов а Dao чтобы реализовывали Storage интерфейсы либо функционал из DAO классов перекинуть в соответствующие storage
А сейчас получается что Stroage классы выступают как еще один сервис прослойка, при этом в них есть логика запросов к базе данных, что вносит очень много путаницы

2023-05-28 10:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/dao/GenresListDao.java
> +public class GenresListDao {
под связующую таблицу создавать Dao не обязательно, этот функционал хорошо зашел бы в Daj фильмов или жанров

2023-05-28 10:21 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/dbtests/FilmorateApplicationTestDb.java
> +    private final DbUserStorage userStorage;
должен быть отдельный тестовый класс для каждого тестируемого хранилища

2023-05-28 10:21 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/dbtests/FilmorateApplicationTestDb.java
> +    public void userCreated() {
именование тестовых методов
[тестируемый метод]_[что должен делать]_[при каких условиях]
последняя часть опциональна
addUser_addUserCorrectly_allDataIsValid

2023-05-30 07:53 UTC, TomattmanYandex requested changes
Комментов все еще много отдельно добавлю пару пунктов
1) по какой то непонятной причине нету проверок пулл реквеста, вкладка checks без пройденных проверок принять не могу
2) не все что помечено с прошлой итерации исправлено
3) классы хранилищ стоит переименовать с DbFilmStorage на FilmDbStorage или FilmStorageDb так гораздо удобнее ведь сразу видишь с чем работает этот  класс (то же и для пользователей)

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        /*likes.add(userId);
закомментированный код не допускается

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        /*film.getLikes().remove(userId);
аналогично

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        /*List<Integer> topFilmsIds = filmStorage.getTopFilms(count);
аналогично

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Mpa getMpaById(Integer id) {
не исправлено

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        //filmStorage.getFilmById(ids.get(0));
закоментированный код

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +            System.out.println("Отсутствуют друзья.");
Вывод в консоль не используем, а используем логирование
да и само сообщение стоит поменять на более осмысленное

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +            System.out.println("Отсутствуют пользователи в БД.");
Вывод в консоль не используем, а используем логирование

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +            System.out.println("Отсутствуют лайки к этому фильму.");
Вывод в консоль не используем, а используем логирование

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +        if (id < 1 || friendId < 1) {
любое числовое значение которое входит в тип integer - валидный id 
стоит убрать эту проверку

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +        Set<Integer> friendsOfUser1 = getFriendListById(id);
стоит сделать метод который будет проверять есть ли конкретный пользователь в друзьях у конкретного пользователя, а не получать все и проверять, что будет если у одного пользователя тысячи друзей?

2023-05-30 07:53 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/dbtests/FilmorateApplicationTestDbFilms.java
> +class FilmorateApplicationTestDbFilms {
стоит переименовать этот класс 
мы тестируем класс DbFilmStorage следовательно назвать стоит просто DBFilmStorageTest
то же касается и следующего класса

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getMostPopularFilm() {
Разве по тз этот метод не должен возвращать 10 топовых фильмов?

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +            Map<Integer, List<Mpa>> filmMpas = getMpasSetBySeveralFilmIds(filmIdList);
Mpa надо получать через join в основном запросе

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    private Map<Integer, Film> filmProcessor(SqlRowSet rowSet) {
не очень понятно по названию что метод делает

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    public Genre getGenreById(Integer id) {
должен быть GenreDbStorage и MpaDbStorage

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    private Map<Integer, Film> filmProcessor(SqlRowSet rowSet) {
жанры должны проставляться через сервис, т.е. сделать почти все то же самое но
1) получаем фильмы с Mpa (на уровне сервиса)
2) вызываем методы которые будут делать примерно то же что в блоке if (filmFound) {
но из GenreDbStorage
3) лайки можно оставить так как есть, чтобы фильм был получен сразу с лайками, (или лучше сделать отдельный метод, который будет работать как в блоке  if (filmFound) { но просто отдельным методом
4) mpa надо получать через join

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    public Map<Integer, List<Genre>> getGenresSetIdBySeveralFilmIds(List<Integer> filmIds) {
этот метод стоит подвигать в GenreDbStorage и чтобы он принимал List<Film> а возвращал List<Film> но с уже проставленными жанрами (логика примерно такая же как тут только прийдется получать список id фильмов в самом методе из списка фильмов, и просатвлять значения прямо в этом методе)

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    public Map<Integer, Set<Integer>> getLikesSetBySeveralFilmIds(List<Integer> filmIds) {
то же что и выше, но не обязательно делать для лайков отдельный класс DAO

2023-05-30 07:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    public Map<Integer, List<Mpa>> getMpasSetBySeveralFilmIds(List<Integer> filmIds) {
mpa должны иметь отдельный класс Dao , но в фильмы Mpa должен проставляться через запрос с join

2023-05-30 19:21 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Mpa getMpaById(Integer id) {
Исправлено: в методе public Mpa getMpaById(Integer id) вызывается mpaDbStorage.getMpaById(id), в котором делается запрос на конкретный фильм: "SELECT * FROM MPA WHERE rating_id = ?"

2023-05-30 19:21 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    private int id;
Исправлено

2023-05-30 19:21 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    private int id;
Исправлено

2023-05-30 19:22 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaAndGenresController.java
> +public class MpaAndGenresController {
Исправлено

2023-05-30 19:22 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Mpa> allMpa = findAllMpa();
Исправлено: в методе public Mpa getMpaById(Integer id) вызывается mpaDbStorage.getMpaById(id), в котором делается запрос на конкретный фильм: "SELECT * FROM MPA WHERE rating_id = ?"

2023-05-30 19:23 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        List<Integer> filmsId = jdbcTemplate.query("SELECT film_id FROM FILMS ORDER BY film_id ASC;", ((rs, rowNum) -> rs.getInt("film_id")));
Исправлено на 1 запрос к БД

2023-05-30 19:24 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        Set<Integer> genresId = genresListDao.getGenresSetIdByFilmId(id);
Исправлено

2023-05-30 19:25 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    public Genre getGenreById(Integer id) {
Переделано: создано GenreDbStorage

2023-05-30 19:26 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    public Mpa getMpaById(Integer id) {
Переделано: создано MpaDbStorage

2023-05-30 19:26 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +//@Component
Исправлено

2023-05-30 19:26 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +//@Component
Исправлено

2023-05-30 19:27 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/dao/FilmsDao.java
> +public class FilmsDao {
Исправлено: созданы только FilmDbStorage, UserDbStorage, GenreDbStorage, MpaDbStorage

2023-05-30 19:27 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/dao/GenresListDao.java
> +public class GenresListDao {
Исправлено

2023-05-30 19:28 UTC, MarinaVolk commented on src/test/java/ru/yandex/practicum/filmorate/dbtests/FilmorateApplicationTestDb.java
> +    private final DbUserStorage userStorage;
Исправлено

2023-05-30 19:28 UTC, MarinaVolk commented on src/test/java/ru/yandex/practicum/filmorate/dbtests/FilmorateApplicationTestDb.java
> +    public void userCreated() {
Исправлено

2023-05-30 19:29 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        /*likes.add(userId);
Исправлено

2023-05-30 19:29 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        /*film.getLikes().remove(userId);
Исправлено

2023-05-30 19:29 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        /*List<Integer> topFilmsIds = filmStorage.getTopFilms(count);
Исправлено

2023-05-30 19:31 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        //filmStorage.getFilmById(ids.get(0));
Исправлено: в методе public Mpa getMpaById(Integer id) вызывается mpaDbStorage.getMpaById(id), в котором делается 1 запрос на конкретный фильм: "SELECT * FROM MPA WHERE rating_id = ?"

2023-05-30 19:31 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +            System.out.println("Отсутствуют друзья.");
Исправлено

2023-05-30 19:32 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +            System.out.println("Отсутствуют пользователи в БД.");
Исправлено

2023-05-30 19:33 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +            System.out.println("Отсутствуют лайки к этому фильму.");
Исправлено

2023-05-30 19:33 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +        if (id < 1 || friendId < 1) {
Исправлено

2023-05-30 19:47 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +        Set<Integer> friendsOfUser1 = getFriendListById(id);
Исправлено

2023-05-30 19:48 UTC, MarinaVolk commented on src/test/java/ru/yandex/practicum/filmorate/dbtests/FilmorateApplicationTestDbFilms.java
> +class FilmorateApplicationTestDbFilms {
Переименовано

2023-05-30 19:50 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getMostPopularFilm() {
Есть метод  public List<Integer> getTopFilms(int count), который возвращает 10 (либо иное указанное количество) топовых фильмов.
Это метод getMostPopularFilm(), который возвращает только 1, самый топовый (для удобства).

2023-05-30 19:53 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +            Map<Integer, List<Mpa>> filmMpas = getMpasSetBySeveralFilmIds(filmIdList);
В классе MpaDbStorage   имеется метод   getMpasSetBySeveralFilmIds(List<Integer> filmIds), в котором с помощью JOIN получаем все MPA для каждого фильма. 
String sql = String.format("" +
                "SELECT " +
                "t.film_id, r.rating_id, r.name " +
                "FROM FILMS as t " +
                "LEFT JOIN MPA as r " +
                "ON t.rating_id = r.rating_id " +
                "WHERE t.film_id = (%d)", film.getId());

2023-05-30 19:58 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    private Map<Integer, Film> filmProcessor(SqlRowSet rowSet) {
Метод filmProcessor() удален.
1) получаем фильмы с Mpa (на уровне сервиса): в сервисе вызываем mpaDbStorage и соответствующий метод для получения МРА
2) в сервисе также вызываем методы из GenreDbStorage
3) лайки тоже добавляем на уровне сервиса вызовом метода addLikesToListOfFilms(films)
4) МРА получаем через JOIN, mpaDbStorage    - >  addMpaToListOfFilms(films) 
 ->   getMpasSetBySeveralFilmIds(List<Integer> filmIds), который использует  JOIN

2023-05-30 19:58 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    public Genre getGenreById(Integer id) {
Добавлено

2023-05-30 20:04 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    public Map<Integer, List<Genre>> getGenresSetIdBySeveralFilmIds(List<Integer> filmIds) {
Исправлено:
public Map<Integer, List<Genre>> getGenresSetIdBySeveralFilmIds(List<Integer> filmIds)  в классе GenreDbStorage это делает.  Однако использую Map для удобства. Вроде бы это не запрещено ТЗ. 
Далее метод    public List<Film> addGenresToListOfFilms(List<Film> films)  возвращает уже лист фильмов для использования.

2023-05-30 20:06 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    public Map<Integer, List<Mpa>> getMpasSetBySeveralFilmIds(List<Integer> filmIds) {
Создан класс MpaDbStorage.  Метод public Map<Integer, List<Mpa>> getMpasSetBySeveralFilmIds(List<Integer> filmIds) использует JOIN:
String sql = String.format("" +
                "SELECT " +
                "t.film_id, r.rating_id, r.name " +
                "FROM FILMS as t " +
                "LEFT JOIN MPA as r " +
                "ON t.rating_id = r.rating_id " +
                "WHERE t.film_id IN (%s)", inSql);

2023-05-30 21:59 UTC, TomattmanYandex requested changes
Привет, все отлично кроме получения Mpa
так как у нас связь один фильм к одному mpa и один mpa ко многим фильмам, когда мы получаем mpa очень удобно получить его вместе с получение данных фильмов, без дополнительных запросов, и это одно из обязательных требований в этой работе

2023-05-30 21:59 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        mpaDbStorage.addMpaToListOfFilms(films);
жанры и лайки отлично, Mpa должны получаться в том же sql запросе что и сами фильмы через join

2023-05-30 21:59 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        mpaDbStorage.addMpaToFilm(film);
c mpa то же что и выше

2023-05-30 21:59 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql = "SELECT * FROM FILMS";
тут должен быть join mpa

2023-05-30 21:59 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql = "SELECT * FROM FILMS WHERE film_id = ?";
и тут должен быть Join mpa

2023-05-31 15:22 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        mpaDbStorage.addMpaToListOfFilms(films);
Исправлено

2023-05-31 15:22 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        mpaDbStorage.addMpaToFilm(film);
Исправлено

2023-05-31 15:22 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql = "SELECT * FROM FILMS";
Добавлено:
public List<Film> getAllFilms() {
        String sql = String.format("" +
                "SELECT t.film_id, " +
                "t.name, " +
                "t.description, t.releaseDate, t.duration, t.rating_id, " +
                "r.rating_id, r.name_mpa " +
                "FROM FILMS as t " +
                "LEFT JOIN MPA as r " +
                "ON t.rating_id = r.rating_id ");

2023-05-31 15:23 UTC, MarinaVolk commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql = "SELECT * FROM FILMS WHERE film_id = ?";
Добавлено:
public Film getFilmById(Integer id) {
        String sql = String.format("" +
                "SELECT t.film_id, " +
                "t.name, " +
                "t.description, t.releaseDate, t.duration, t.rating_id, " +
                "r.rating_id, r.name_mpa " +
                "FROM FILMS as t " +
                "LEFT JOIN MPA as r " +
                "ON t.rating_id = r.rating_id " +
                "WHERE t.film_id = (%d)", id);

2023-05-31 21:12 UTC, TomattmanYandex approved these changes
Принято

2023-05-31 21:24 UTC, merged